### ISSUE TITLE
Compiling on MacOSX

### ISSUE THREAD

**Issue by blatrob** [sonoro1234/MyUGens#2]
During compile, this error is thrown: 

[ 30%] Linking CXX shared module SonLPC.scx
Undefined symbols for architecture x86_64:
  "_vDSP_vadd", referenced from:
      _SonLPCSynth_next in SonLPC.cpp.o
      _SonLPCSynthIn_next in SonLPC.cpp.o
      _SonLPCError_next in SonLPC.cpp.o
      _SonLPCMorph_next in SonLPC.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [SonLPC/SonLPC.scx] Error 1
make[1]: *** [SonLPC/CMakeFiles/SonLPC.dir/all] Error 2
make: *** [all] Error 2

**Comment by sonoro1234** [comment]
Hi Geoff,

Congratulations for new github account.
I guess that this happens after my commit for adding vDSP? (It seems so as compile phase succeeds now)
Now it need to succeed in linking also, I am going to find out and tell you

**Comment by sonoro1234** [comment]
Could you give it a try now?

**Comment by blatrob** [comment]
Hi Victor -
Thanks for walking me through this. There's a new error now, not sure if I should make a separate issue? 

[ 50%] Building CXX object AdachiAyers/CMakeFiles/AdachiAyers.dir/AdachiAyers.cpp.o
/Users/geob/Desktop/MyUGens-master/AdachiAyers/AdachiAyers.cpp:20:10: fatal error: 
      'simd_binary_arithmetic.hpp' file not found
#include "simd_binary_arithmetic.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [AdachiAyers/CMakeFiles/AdachiAyers.dir/AdachiAyers.cpp.o] Error 1
make[1]: *** [AdachiAyers/CMakeFiles/AdachiAyers.dir/all] Error 2
make: *** [all] Error 2

**Comment by sonoro1234** [comment]
> Thanks for walking me through this. There's a new error now, not sure if I should make a separate issue?

Thanks for your work on this. I need someone to try building on mac osx. Dont make separate issue, I will change title.

> 'simd_binary_arithmetic.hpp' file not found

This file should be in supercollider/external_libraries/nova-simd (check it)
If it is not, that would mean that you havent cloned supercollider repository with recursive option for getting submodules. Try to clone supercollider recursively 

(I saw in the supercollider mail list that you got supercollider source in zip format, sometimes it lefts submodules out. You should do a git clone to be able to compile supercollider or AdachiAyers)

`git clone --recursive https://github.com/SuperCollider/SuperCollider.git`

if the clone is already done you can use then from supercollider repo folder:

`git submodule update --init --recursive`

**Comment by blatrob** [comment]
Alright, after doing the cloning SC as specified, I was able to do a build that seems to have "completed", but there are several warnings. When I dragged the build into the Extensions folder of SuperCollider and recompiled, the new uGens did not integrate. 

-- Build files have been written to: /Users/geob/Desktop/MyUGens-master/build
geob-MBP:build geob$ make
Scanning dependencies of target DWGClarinet
[  3%] Building CXX object DWGClarinet/CMakeFiles/DWGClarinet.dir/DWGClarinet.cpp.o
[  7%] Linking CXX shared module DWGClarinet.scx
[  7%] Built target DWGClarinet
Scanning dependencies of target DWGFlute
[ 11%] Building CXX object DWGFlute/CMakeFiles/DWGFlute.dir/DWGFlute.cpp.o
[ 15%] Linking CXX shared module DWGFlute.scx
[ 15%] Built target DWGFlute
Scanning dependencies of target KLJunction
[ 19%] Building CXX object KLJunction/CMakeFiles/KLJunction.dir/KLJunction.cpp.o
[ 23%] Linking CXX shared module KLJunction.scx
[ 23%] Built target KLJunction
Scanning dependencies of target SonLPC
[ 26%] Building CXX object SonLPC/CMakeFiles/SonLPC.dir/SonLPC.cpp.o
[ 30%] Linking CXX shared module SonLPC.scx
[ 30%] Built target SonLPC
Scanning dependencies of target Karplus
[ 34%] Building CXX object Karplus/CMakeFiles/Karplus.dir/Karplus.cpp.o
/Users/geob/Desktop/MyUGens-master/Karplus/Karplus.cpp:152:1: warning: 
      control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
[ 38%] Linking CXX shared module Karplus.scx
[ 38%] Built target Karplus
Scanning dependencies of target IIRf
[ 42%] Building CXX object IIRf/CMakeFiles/IIRf.dir/IIRf.cpp.o
[ 46%] Linking CXX shared module IIRf.scx
[ 46%] Built target IIRf
Scanning dependencies of target AdachiAyers
[ 50%] Building CXX object AdachiAyers/CMakeFiles/AdachiAyers.dir/AdachiAyers.cpp.o
[ 53%] Linking CXX shared module AdachiAyers.scx
[ 53%] Built target AdachiAyers
Scanning dependencies of target PitchTracker
[ 57%] Building CXX object PitchTracker/CMakeFiles/PitchTracker.dir/PitchTracker.cpp.o
/Users/geob/Desktop/MyUGens-master/PitchTracker/PitchTracker.cpp:309:1: warning: 
      control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
[ 61%] Linking CXX shared module PitchTracker.scx
[ 61%] Built target PitchTracker
Scanning dependencies of target PluckSynth
[ 65%] Building CXX object PluckSynth/CMakeFiles/PluckSynth.dir/PluckSynth.cpp.o
[ 69%] Linking CXX shared module PluckSynth.scx
[ 69%] Built target PluckSynth
Scanning dependencies of target MembraneV
[ 73%] Building CXX object MembraneV/CMakeFiles/MembraneV.dir/MembraneV.cpp.o
[ 76%] Building C object MembraneV/CMakeFiles/MembraneV.dir/Membrane_shape.c.o
[ 80%] Linking CXX shared module MembraneV.scx
[ 80%] Built target MembraneV
Scanning dependencies of target MyPlucked
[ 84%] Building CXX object MyPlucked/CMakeFiles/MyPlucked.dir/MyPlucked.cpp.o
[ 88%] Linking CXX shared module MyPlucked.scx
[ 88%] Built target MyPlucked
Scanning dependencies of target DWGReverb
[ 92%] Building CXX object DWGReverb/CMakeFiles/DWGReverb.dir/PartitionedConvolutionTrig.cpp.o
[ 96%] Building CXX object DWGReverb/CMakeFiles/DWGReverb.dir/Reverb.cpp.o
[100%] Linking CXX shared module DWGReverb.scx
[100%] Built target DWGReverb
geob-MBP:build geob$

**Comment by sonoro1234** [comment]
Those warnings are not relevant althought later I will make them disappear.

After cmake with `-DCMAKE_INSTALL_PREFIX="./scinstall"` you should type `make install` then move everything inside scinstall to the relevant folder in your system (probably Extension).

As I only use MyUGens with Lua2SC most of them dont have sc classes (#1) but MembraneV and DWGReverb have sc classes so they sould appear in SC Help system with some examples to try.

**Comment by blatrob** [comment]
OK - I believe that all worked. Thank you. 
I would specifically be interested in the Pitch Tracker uGen and the DWGClarinet and Flutes, if you are looking for someone to test on Mac further.

**Comment by sonoro1234** [comment]
I have done DWGClarinet addition plus some other sc classes/help corrections (included in DWGReverb that is a submodule so you should do a recursive clone or git submodule update --init --recursive)

Also MyPlucked addition (sample  with Lua2SC at https://soundcloud.com/victor-bombi/morning-in-india)
DWGFlute addition.
PitchTracker addition.

Stop for now!!

**Comment by blatrob** [comment]
Great! I'll give it a shot later this evening.

**Comment by blatrob** [comment]
Everything seems to be working on my end! Thanks!
