### ISSUE TITLE
build error  'simd_binary_arithmetic.hpp' file not found

### ISSUE THREAD

**Issue by cdbzb** [sonoro1234/MyUGens#4]
greetings!

trying to build on mac and mostly going well!

I receive the following error however:

/tmp/MyUGens/AdachiAyers/AdachiAyers.cpp:20:10: fatal error: 'simd_binary_arithmetic.hpp' file not found

cheers and thanks for sharing these!

**Comment by sonoro1234** [comment]
'simd_binary_arithmetic.hpp'  should be in `supercollider\external_libraries\nova-simd`
Check if the file is there. If it is not could be because you forgot to git submodule update recursive when getting supercollider repository

**Comment by cdbzb** [comment]
THANK YOU!

the DWG Reverb is a dream!
