### ISSUE TITLE
Does not build on arm

### ISSUE THREAD

**Issue by madskjeldgaard** [sonoro1234/MyUGens#5]
Hello!

First of all thank you for these awesome plugins! I've added them to the AUR so that users on arch based systems can install simply by invoking `yay -S supercolider-sonoro1234-ugens-git`. 

I discovered an issue though when building on arm (raspberry pi 4/arch linux):
```
c++: error: unrecognized command-line option '-msse2'
c++: error: unrecognized command-line option '-mstackrealign'
c++: error: unrecognized command-line option '-mfpmath=sse'
make[2]: *** [DWGClarinet/CMakeFiles/DWGClarinet.dir/build.make:76: DWGClarinet/CMake
Files/DWGClarinet.dir/DWGClarinet.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:296: DWGClarinet/CMakeFiles/DWGClarinet.dir/all] E
rror 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by sonoro1234** [comment]
Can you try https://github.com/sonoro1234/MyUGens/tree/armcompile ?

**Comment by madskjeldgaard** [comment]
> Can you try https://github.com/sonoro1234/MyUGens/tree/armcompile ?

Yep it gets a lot further with this, but still not there yet:
```
[ 80%] Built target MembraneV
[ 84%] Building CXX object MyPlucked/CMakeFiles/MyPlucked.dir/MyPlucked.cpp.o
c++: error: unrecognized command-line option '-msse2'
c++: error: unrecognized command-line option '-mstackrealign'
c++: error: unrecognized command-line option '-mfpmath=sse'
make[2]: *** [MyPlucked/CMakeFiles/MyPlucked.dir/build.make:76: MyPlucked/CMakeFiles/MyPlucked.dir/MyPlucked.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:556: MyPlucked/CMakeFiles/MyPlucked.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'supercollider-sonoro1234-ugens-git-r52.373594f-1':
:: Packages failed to build: supercollider-sonoro1234-ugens-git-r52.373594f-1

```

**Comment by sonoro1234** [comment]
could you try now? (submodule update needed for dwgreverb)

**Comment by madskjeldgaard** [comment]
[ 88%] Built target MyPlucked
[ 92%] Building CXX object DWGReverb/CMakeFiles/DWGReverb.dir/PartitionedConvolutionTrig.cpp.o
c++: error: unrecognized command-line option '-msse2'
c++: error: unrecognized command-line option '-mstackrealign'
c++: error: unrecognized command-line option '-mfpmath=sse'
make[2]: *** [DWGReverb/CMakeFiles/DWGReverb.dir/build.make:76: DWGReverb/CMakeFiles/DWGReverb.dir/PartitionedConvolutionTrig.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:582: DWGReverb/CMakeFiles/DWGReverb.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'supercollider-sonoro1234-ugens-git-r52.373594f-1':
:: Packages failed to build: supercollider-sonoro1234-ugens-git-r52.373594f-1

**Comment by madskjeldgaard** [comment]
It reaches dwgreverb now but then fails. So it's almost working !

**Comment by sonoro1234** [comment]
Dwgreverb should not fail. use submodule update or delete repo and fresh new clone, please.

**Comment by madskjeldgaard** [comment]
Ah sorry I reviewed submodules before checking out this branch. Works now !

**Comment by sonoro1234** [comment]
@madskjeldgaard Thanks for reporting and testing. Fixed now in master.

**Comment by madskjeldgaard** [comment]
Thanks !
